"$schema" = 'https://starship.rs/config-schema.json'

[directory]
truncation_length = 100
truncate_to_repo = false

[hostname]
ssh_only = false

[username]
show_always = true
format = '[$user]($style) '
